// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ActivityFilter struct {
	ID        *string `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	StartTime *string `json:"startTime,omitempty"`
	EndTime   *string `json:"endTime,omitempty"`
	EventID   *string `json:"eventID,omitempty"`
}

type EventFilter struct {
	ID        *string `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	EndDate   *string `json:"endDate,omitempty"`
	Location  *string `json:"location,omitempty"`
	Type      *string `json:"type,omitempty"`
}

type ExpenseFilter struct {
	ID       *string `json:"id,omitempty"`
	ItemName *string `json:"itemName,omitempty"`
	Type     *string `json:"type,omitempty"`
}

type Mutation struct {
}

type Pagination struct {
	Limit     *int    `json:"limit,omitempty"`
	Offset    *int    `json:"offset,omitempty"`
	SortBy    *string `json:"sortBy,omitempty"`
	SortOrder *string `json:"sortOrder,omitempty"`
}

type ParticipantFilter struct {
	ID     *string `json:"id,omitempty"`
	UserID *string `json:"userId,omitempty"`
	Role   *string `json:"role,omitempty"`
}

type Query struct {
}

type UpdateActivity struct {
	Name        *string `json:"name,omitempty"`
	StartTime   *string `json:"startTime,omitempty"`
	EndTime     *string `json:"endTime,omitempty"`
	Description *string `json:"description,omitempty"`
	EventID     *int    `json:"eventId,omitempty"`
}

type UpdateEvent struct {
	Name        *string `json:"name,omitempty"`
	StartDate   *string `json:"startDate,omitempty"`
	EndDate     *string `json:"endDate,omitempty"`
	Location    *string `json:"location,omitempty"`
	Type        *string `json:"type,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateExpense struct {
	ItemName    *string `json:"itemName,omitempty"`
	Cost        *int    `json:"cost,omitempty"`
	Description *string `json:"description,omitempty"`
	Type        *string `json:"type,omitempty"`
	EventID     *int    `json:"eventID,omitempty"`
}

type UpdateParticipant struct {
	UserID  *int    `json:"userId,omitempty"`
	EventID *int    `json:"eventId,omitempty"`
	Role    *string `json:"role,omitempty"`
}

type UserFilter struct {
	ID      *string `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Email   *string `json:"email,omitempty"`
	PhoneNo *string `json:"phoneNo,omitempty"`
}
